### ISSUE TITLE
Nao sei oque fazer

### ISSUE THREAD

**Issue by GabriellPereira** [Pedtoledo/teste-aula1402#1]
ola @Pedtoledo e @WilgnerDelfino , oque temos que fazer agora ?

**Comment by Pedtoledo** [comment]
nao sei


________________________________
De: Filiciel Pereivid <notifications@github.com>
Enviado: terça-feira, 14 de fevereiro de 2017 14:29:32
Para: Pedtoledo/teste-aula1402
Cc: PEDRO HENRIQUE TOLEDO; Mention
Assunto: [Pedtoledo/teste-aula1402] Nao sei oque fazer (#1)


ola @Pedtoledo<https://github.com/Pedtoledo> e @WilgnerDelfino<https://github.com/WilgnerDelfino> , oque temos que fazer agora ?

**Comment by Filicio** [comment]
nem eu

**Comment by Filicio** [comment]
ou galera :new_moon_with_face:
